<?php

namespace two_plug\sdk_fitbank\Helpers;

const GENDER_MALE = 0;
const GENDER_FEMALE = 1;
const GENDER_OTHER = 2;

const MARITAL_STATUS_NOTMARRIED = 0;
const MARITAL_STATUS_MARRIED = 1;
const MARITAL_STATUS_DIVORCED = 2;
const MARITAL_STATUS_SEPARATE = 3;
const MARITAL_STATUS_WIDOWER = 4;
const MARITAL_STATUS_SINGLE = 5;
const MARITAL_STATUS_OTHER = 6;

const COMPANY_TYPE_SA = 0;
const COMPANY_TYPE_LTDA = 1;
const COMPANY_TYPE_MEI = 2;

const DOCUMENT_TYPE_IDENTITY_DOCUMENT_FRONT = 0;
const DOCUMENT_TYPE_TAXNUMBER = 1;
const DOCUMENT_TYPE_PROOF_OF_RESIDENCE = 2;
const DOCUMENT_TYPE_CNH = 3;
const DOCUMENT_TYPE_CNPJ = 4;
const DOCUMENT_TYPE_SOCIAL_CONTRACT = 5;
const DOCUMENT_TYPE_LETTER_OF_ATTORNE = 6;
const DOCUMENT_TYPE_IDENTITY_DOCUMENT_VERSE = 7;
const DOCUMENT_TYPE_IDENTITY_DOCUMENT = 10;
const DOCUMENT_TYPE_MINUTE_OF_CONSTITUTION = 11;

const DOCUMENT_FORMAT_PDF = 0;
const DOCUMENT_FORMAT_JPG = 1;
const DOCUMENT_FORMAT_JPEG = 2;
const DOCUMENT_FORMAT_TXT = 3;
const DOCUMENT_FORMAT_PNG = 4;